### ISSUE TITLE
Add support for combining diaerasis below

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-serif-pro#41]
The usage of diaerasis below have been documented in the Dictionary of the Foochow dialect, which uses a [romanization](https://en.wikipedia.org/wiki/Foochow_Romanized) to transliterate Fozhou dialect of Eastern Min Chinese. However it doesn’t works well with Source Serif Pro.
![screenshot](https://user-images.githubusercontent.com/10364351/49957654-6850aa80-ff00-11e8-99dd-4f8046974d85.PNG)

**Comment by frankrolf** [comment]
Combining dieresis below (U+0324) is supported in Source Serif.
<img width="756" alt="image" src="https://user-images.githubusercontent.com/2049645/49959386-b15b2b80-ff0d-11e8-82a8-dfd24f6aa113.png">

**Comment by miguelsousa** [comment]
@frankrolf which version did you use?

**Comment by frankrolf** [comment]
Should have included that: I am testing this with the latest available version, which is 2.007. However, even earlier versions, such as 2.000 should support the same combination.

I tested the combinations in InDesign CC 2019.

**Comment by frankrolf** [comment]
This bug is very similar to #42 – allowing for more than one combining accent to be added to the base glyph. While InDesign is more permissive in this scenario, it is true that other layout engines (CoreText in Safari, and HarfBuzz in Chrome) don’t work as expected. It is something I will investigate, I’ll also rename #42 to be a more universal summary of this particular enhancement request.

**Comment by svenper** [comment]
It would also be nice to have Ṳ and ṳ as separate letters (`U+1E72` and `U+1E73`).
