### ISSUE TITLE
dashes not printing

### ISSUE THREAD

**Issue by hooseyfloot** [adobe-fonts/source-serif-pro#47]
Hi. The en and em dashes in the latest version are showing on screen (in InDesign) but not printing on the printer. Any suggestions why that might be? (Dashes are printing correctly for other fonts on the system.)

The font is looking lovely BTW.

**Comment by hooseyfloot** [comment]
Sorry, revise that - it's when I print via a pdf - the dashes go missing from the pdf (they print fine direct from InDesign).

**Comment by miguelsousa** [comment]
Same as #44.

**Comment by hooseyfloot** [comment]
Thanks for this. One clarification though: the workaround on #44  suggests using the OTF version. That's what I'm using but not getting the dashes.

**Comment by miguelsousa** [comment]
Go to the menu **Type > Find Font...** then select Source Serif and click on the **More Info** button. The dialog should look similar to this:
<img width="587" alt="sserif_find_font" src="https://user-images.githubusercontent.com/2119742/50876005-bdf16900-137f-11e9-9a1b-2816898fdb38.png">

Does the **Path** line end in `.otf` for you?
I'm asking because as you can see from my screenshot I have a `.ttf` font installed and it's listed as **Source Serif Pro (OTF) Regular**.

**Comment by hooseyfloot** [comment]
Thanks Miguel
I'm on a Windows machine and use a font management program to temporarily load certain fonts.
Here are the font's details from that program (NexusFont)...


But actually - that got me thinking. I copied the font file into the Windows font directory to make it permanently installed and, sure enough, the pdf export and printing worked fine.
So that solves my problem... I'm not sure why it didn't work with the temporary loading though - I haven't encountered that issue with any other fonts.
All the best - and thanks for your hard work with the development of this font.






 

    On Wednesday, 9 January 2019, 5:03:38 PM NZDT, Miguel Sousa <notifications@github.com> wrote:  
 
 
Go to the menu Type > Find Font... then select Source Serif and click on the More Info button. The dialog should look similar to this:


Does the Path line end in .otf for you?
I'm asking because as you can see from my screenshot I have a .ttf font installed and it's listed as Source Serif Pro (OTF) Regular.
