### ISSUE TITLE
Standardize Point Size & Line Spacing

### ISSUE THREAD

**Issue by atntmori** [adobe-fonts/source-serif-pro#49]
Hello,

I was using Source Serif Pro interchangeably with Source Sans Pro when I noticed that their optical sizes and line spacing were different, even though I had set them to the same point size. Source Sans Pro and Source Code already share the same absolute size and line spacing, so it would be great if Source Serif could be standardized in line with the other two typefaces.

Thank you for the great work with these open-source typefaces!

**Comment by frankrolf** [comment]
Source Serif was developed to work together with Source Sans. I was a little surprised by your statement and made some tests, the results of which are attached here. I don’t think I perceive a difference in optical size.

About the line spacing – it is possible for it to be different – the line spacing is mostly calculated through outlines found in the font. Since Source Serif needs to have significantly higher contrast (as a serif face), it’ll also need longer ascenders & descenders. Changing Source Serif’s metrics in favor of matching Source Sans is difficult, because it will likely result in clipping.

Various questions for you:
- which environment are you reporting about?
- is it possible for you to set the line spacing manually in that environment?
- can you illustrate your question with screenshots?

Thank you!

![screen shot 2019-02-07 at 14 13 55](https://user-images.githubusercontent.com/2049645/52413773-c950c500-2ae2-11e9-98d5-fa7ea9179df5.png)
![screen shot 2019-02-07 at 14 13 34](https://user-images.githubusercontent.com/2049645/52413774-c9e95b80-2ae2-11e9-912b-6043d0225f29.png)
![screen shot 2019-02-07 at 14 13 01](https://user-images.githubusercontent.com/2049645/52413775-c9e95b80-2ae2-11e9-890f-2e7352e1f9f2.png)

**Comment by atntmori** [comment]
Sorry for the confusion! I mainly use these typefaces in word processing, and I was surprised by how much space Source Serif took up in comparison to Source Sans. 

In other typeface superfamilies like IBM Plex, there isn't as much variance in point size and line height between the serif and sans-serif versions, which results in a similar amount of horizontal space taken. While I was able to find families whose serif version had similar metrics to Source Serif, the sans-serif version matched in point size and line height, unlike with Source Sans.

When I looked closer at the typefaces, Source Serif appeared to have a slightly taller cap height than Source Sans. While that might seem insignificant, changing the typeface of a header could require changing the point size by a half to full point in order to achieve visual parity. Over the span of a longer paper, changing the body text font significantly alters the length of the paper. While it's possible to manually alter the line length by measuring in points, the default spacing (single, 1.5, double) in Source Serif is very loose compared to Source Sans, and the baseline is slightly lower.

I'm a big fan of the Source typeface designs and the work you all do! I was just thinking of how to bring more consistency to the metrics of these typefaces since they're part of a superfamily. Changing the outlines of Source Serif isn't necessary. It's common for serif variants to be slightly wider than their sans-serif counterparts, so Source Serif is perfectly fine in that respect. Source Sans was designed first, so I was thinking that Source Serif should have matching cap and line heights.

<img width="989" alt="screen shot 2019-02-07 at 7 53 19 am" src="https://user-images.githubusercontent.com/47303206/52424209-5ded0000-2aae-11e9-9bdd-b28ff6b9f773.png">
<img width="1020" alt="screen shot 2019-02-07 at 7 54 33 am" src="https://user-images.githubusercontent.com/47303206/52424212-5ded0000-2aae-11e9-9adc-29d41a80fbc0.png">
![Uploading Screen Shot 2019-02-07 at 7.54.42 AM.png…]()
<img width="1044" alt="screen shot 2019-02-07 at 7 54 56 am" src="https://user-images.githubusercontent.com/47303206/52424214-5ded0000-2aae-11e9-9135-ecf127748746.png">

**Comment by frankrolf** [comment]
Thank you for the explanation and examples. 

As for the horizontal space taken, there is really not much I can do without distorting the design significantly. Serif typefaces have different requirements from Sans Serifs, the presence of serifs alone will make all of them run wider than their Sans Serif counterparts. That said, Source Serif is not on the wide side for a serif design.

Cap height: 
While it may be intriguing to compare the amount of pixels or points a shape is occupying from top to bottom, equal height doesn’t automatically mean equal appearance. The caps of Source Serif are taller because of their contrast and resulting additional whitespace. If they would measure the exact same height as Source Sans’ caps, they would appear visually smaller.

Line spacing:
You write “the baseline is lower”. Again – which environment are you reporting about?
The “default” spacing is not necessarily a decision made by the type designer, but a result of various factors, such as the tallest glyphs in the font (incl. accented glyphs). It is possible that Source Serif has taller glyphs than Source Sans, nevertheless the baseline should not be lower.
Please note that the vertical spacing how you experience it is not built into the fonts themselves, but decided for by the editing application. _How_ the lines are calculated, varies from application to application, that’s why it would be important to know your setup.

**Comment by atntmori** [comment]
I use Apple's Pages word processor, but thank you for explaining the mechanics of the typeface design and how editing applications can vary vertical spacing.

Taking another look, I noticed that the heavier weights of Source Sans and Serif are more similar in size to my eye, whereas the lighter weights vary greater in horizontal space.

It's not as big of an issue as I thought, as I can manually control line spacing, so I'll close this issue. Thank you for walking me through this!

**Comment by frankrolf** [comment]
Your observation is correct – Source Serif uses an “intermediate master” for the text weight, and controls the interpolation progression that way. 
The letter widths don’t really change anymore toward the light end, just the weight does. In my opinion, this creates better performance in text weights (the area that matters most for this kind of design), and allows me to not make too many compromises in ExtraLight and Heavy masters.
Source Sans uses linear interpolation from an ExtraLight master to a Heavy master.

**Comment by FloraCanou** [comment]
I second this. In LibreOffice I use 10.5 points for Source Serif and 11 for Source Sans and they look approximately the same.
